[package]
name = "minecraft-client-rs"
version = "0.1.0"
authors = ["Will Roberts"]
edition = "2018"
description = "A client for the Minecraft RCON protocol."
license = "GNU General Public License v3.0"

[dependencies]
